### ISSUE TITLE
Left title jumps, the right title does not

### ISSUE THREAD

**Issue by Hooorny** [JakeWharton/ViewPagerIndicator#69] opened 2012-03-05 10:08 UTC
This belongs to the TitlePagerIndicator:

When I swipe between screens and the middle title needs too much space to show all titles on screen, the left title is "jumping" when I swipe to the left, while the right title is moving smoothly when I swipe to the right until the middle title has enough space to be fully shown.

**Comment by sealskej** [comment] 2012-03-16 22:19
I can certainly confirm this.

**Comment by sealskej** [comment] 2012-03-18 14:01
Try to put long Strings as titles and you will see it ;)

**Comment by evgenpush** [comment] 2012-03-20 05:44
when will be bug fixed?

**Comment by scompt** [comment] 2012-07-27 12:21
This is a duplicate of #101 as far as I can tell.

**Closed as completed** 2012-08-29 03:57 UTC
