### ISSUE TITLE
Invalid POM: 'dependencies.dependency.version' for com.google.android:support-v4:jar is missing

### ISSUE THREAD

**Issue by achuinard** [JakeWharton/ViewPagerIndicator#85] opened 2012-04-26 07:42 UTC
I get the following error after running mvn -X clean package:

```
[WARNING] The POM for com.viewpagerindicator:library:apklib:2.2.3 is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model for com.viewpagerindicator:library:2.2.3
[ERROR] 'dependencies.dependency.version' for com.google.android:support-v4:jar is missing. @ 
```

I am including the lib as follows:

``` xml
<dependency>
  <groupId>com.viewpagerindicator</groupId>
  <artifactId>library</artifactId>
  <version>2.2.3</version>
  <type>apklib</type>
</dependency>
```

Also, oddly enough IntelliJ can't pick up on the library.

**Comment by JakeWharton** [comment] 2012-05-18 09:04
Still having this problem? I cannot reproduce at all.

**Comment by JakeWharton** [comment] 2012-05-19 07:45
Closing for now.

**Closed as completed by JakeWharton** 2012-05-19 07:45 UTC
