### ISSUE TITLE
Come back to titlePageIndicator after orientation changed

### ISSUE THREAD

**Issue by hazse** [JakeWharton/ViewPagerIndicator#54] opened 2012-01-27 08:28 UTC
I have fuond a bug. To reproduce do this steps:
1.Go to last page in titlePageIndicator
2. Leave the Activity (not close just open some other activity)
3. change the orientation of screen
4. go back to titlePageIndicator via Back button
5. Screen is totally random indiscriminate - either Title is in wron place or pager view is missing or showed on ly the half view

It can be fix via a small gesture ti right but its very strange and interesting

**Comment by JakeWharton** [comment] 2012-05-19 07:47
I cannot reproduce this on `dev`. I think it was fixed with another commit.

**Closed as completed by JakeWharton** 2012-05-19 07:47 UTC
Labels: Bug Report
