### ISSUE TITLE
Rare NullPointerException via TitlePageIndicator.onTouchEvent

### ISSUE THREAD

**Issue by howardb173** [JakeWharton/ViewPagerIndicator#72] opened 2012-03-11 18:30 UTC
Hi, been using ViewPagerIndicator for a couple of months now in my app. But noticed a sprinkling of these errors reported via acra:

java.lang.NullPointerException
    at android.support.v4.view.ViewPager.a(SourceFile:1733)
    at com.viewpagerindicator.TitlePageIndicator.onTouchEvent(SourceFile:496)
    at android.view.View.dispatchTouchEvent(View.java:4688)

I'm using v2.2.2. Only reported on one device "PantechP4100" running 3.2.1(13)

TitlePageIndicator:

```
public boolean onTouchEvent(android.view.MotionEvent ev) {
    if ((mViewPager == null) || (mViewPager.getAdapter().getCount() == 0)) {
        return false;
    }

    final int action = ev.getAction();

    switch (action & MotionEventCompat.ACTION_MASK) {
        case MotionEvent.ACTION_DOWN:
            mActivePointerId = MotionEventCompat.getPointerId(ev, 0);
            mLastMotionX = ev.getX();
            break;

        case MotionEvent.ACTION_MOVE: {
            final int activePointerIndex = MotionEventCompat.findPointerIndex(ev, mActivePointerId);
            final float x = MotionEventCompat.getX(ev, activePointerIndex);
            final float deltaX = x - mLastMotionX;

            if (!mIsDragging) {
                if (Math.abs(deltaX) > mTouchSlop) {
                    mIsDragging = true;
                }
            }

            if (mIsDragging) {
                if (!mViewPager.isFakeDragging()) {
                    mViewPager.beginFakeDrag();
                }

                mLastMotionX = x;

                mViewPager.fakeDragBy(deltaX);    <---- EXCEPTION BUBBLES HERE
            }

            break;
        }
```

ViewPager:

```
public void fakeDragBy(float xOffset) {
    if (!mFakeDragging) {
        throw new IllegalStateException("No fake drag in progress. Call beginFakeDrag first.");
    }

    mLastMotionX += xOffset;
    float scrollX = getScrollX() - xOffset;
    final int width = getWidth();
    final int widthWithMargin = width + mPageMargin;

    final float leftBound = Math.max(0, (mCurItem - 1) * widthWithMargin);
    final float rightBound =
            Math.min(mCurItem + 1, mAdapter.getCount() - 1) * widthWithMargin;
    if (scrollX < leftBound) {
        scrollX = leftBound;
    } else if (scrollX > rightBound) {
        scrollX = rightBound;
    }
    // Don't lose the rounded component
    mLastMotionX += scrollX - (int) scrollX;
    scrollTo((int) scrollX, getScrollY());
    pageScrolled((int) scrollX);

    // Synthesize an event for the VelocityTracker.
    final long time = SystemClock.uptimeMillis();
    final MotionEvent ev = MotionEvent.obtain(mFakeDragBeginTime, time, MotionEvent.ACTION_MOVE,
            mLastMotionX, 0, 0);
    mVelocityTracker.addMovement(ev);     <--- EXCEPTION HERE
    ev.recycle();
}
```

Looks like mVelocityTracker hasn't been initialised. I'm guessing this is a bit of a freaky scenario to trigger that as the ViewPager and ViewPagerIndiciator seem to be a very resilient and happy partnership.

Let me know if I can help further..?

**Comment by dimsuz** [comment] 2012-04-09 13:43
We have seen this bug too. It was reproduced only once so far - by very quick swiping back and forth.

**Comment by JakeWharton** [comment] 2012-05-19 07:48
Should be fixed with new drag code in `dev`.

**Closed as completed by JakeWharton** 2012-05-19 07:48 UTC

**Comment by larham** [comment] 2012-11-05 23:01
Just got this stack from a device in the field using ViewPagerIndicator 4.2.1.  Is this the same as the previous reports?  Did the fix in 'dev' get into 4.2.1?

thanks,

## Larry

Throwable occurred: java.lang.NullPointerException
    at android.support.v4.view.ViewPager.fakeDragBy(SourceFile:2118)
    at com.viewpagerindicator.TitlePageIndicator.onTouchEvent(SourceFile:573)
    at android.view.View.dispatchTouchEvent(View.java:5579)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1987)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1734)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1965)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1734)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1987)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1734)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1965)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1734)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1982)
    at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1441)
    at android.app.Activity.dispatchTouchEvent(Activity.java:2421)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1930)
    at android.view.View.dispatchPointerEvent(View.java:5759)
    at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:2970)
    at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2529)
    at android.view.ViewRootImpl.processInputEvents(ViewRootImpl.java:869)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:883)
    at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2505)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:4945)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
    at dalvik.system.NativeStart.main(Native Method)

sys: 

android.version: 4.0.3
brand/model: sprint/PH44100

**Comment by chap19150** [comment] 2012-12-07 15:16
I just got this NullPointerException on the CirclePageIndicator also using version 4.2.1
Running android 4.1.1

// java.lang.NullPointerException
//      at android.support.v4.view.ViewPager.fakeDragBy(ViewPager.java:1733)
//      at com.viewpagerindicator.CirclePageIndicator.onTouchEvent(CirclePageIndicator.java:305)
//      at android.view.View.dispatchTouchEvent(View.java:7127)
//      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2198)
//      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
//      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
//      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
//      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
//      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
//      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
//      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
//      at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindo
w.java:1925)
//      at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:137
9)
//      at android.app.Activity.dispatchTouchEvent(Activity.java:2396)
//      at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.jav
a:1873)
//      at android.view.View.dispatchPointerEvent(View.java:7307)
//      at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3172)
//      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3117)
//      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4153)
//      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4132)
//      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4224)
//      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
//      at android.os.MessageQueue.nativePollOnce(Native Method)
//      at android.os.MessageQueue.next(MessageQueue.java:125)
//      at android.os.Looper.loop(Looper.java:124)
//      at android.app.ActivityThread.main(ActivityThread.java:4745)
//      at java.lang.reflect.Method.invokeNative(Native Method)
//      at java.lang.reflect.Method.invoke(Method.java:511)
//      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
//      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
//      at dalvik.system.NativeStart.main(Native Method)

**Comment by tyvsmith** [comment] 2012-12-10 19:51
Seeing the same stacktrace using 4.2.1 from a users device.  No repro steps given. Looks to be throwing an NPE on mVelocityTracker.addMovement(ev); (ViewPager.java:2118)

**Comment by emmby** [comment] 2013-02-11 04:05
I can confirm I'm also seeing it in 2.4.1 on ViewPager.java:2118 when using monkey

**Comment by Tolriq** [comment] 2013-03-26 10:37
I have also some report of this with last dev branch (Last support lib too)

STACK_TRACE=java.lang.NullPointerException
at android.support.v4.view.ViewPager.a(SourceFile:2287)
at com.viewpagerindicator.TitlePageIndicator.onTouchEvent(SourceFile:573)
at android.view.View.dispatchTouchEvent(View.java:7246)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1953)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1405)
at android.app.Activity.dispatchTouchEvent(Activity.java:2410)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1901)
at android.view.View.dispatchPointerEvent(View.java:7426)
at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3220)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3165)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4292)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4271)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4363)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:125)
at android.os.Looper.loop(Looper.java:124)
at android.app.ActivityThread.main(ActivityThread.java:5041)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
at dalvik.system.NativeStart.main(Native Method)

**Comment by jonschmidt** [comment] 2013-05-28 00:17
Just curious, is this issue going to get anymore attention or should I fork and look at fixing it myself? I have an app with ~ 5m users and we see this crash about 800 - 1k times per week.

**Comment by Tolriq** [comment] 2013-05-28 10:35
The easy way is to do like me get the source and add a little patch.
Since I was not able to really understand or correctly repair I just addded a try catch around the mViewPager.fakeDragBy(deltaX); and did not propose a PR.

**Comment by mshipton** [comment] 2013-06-17 10:24
I have experienced this same problem. I run a small animation that "nudges" the content of a ViewPager, so the user can see there is some new content in the offscreen View.

The problem occurs for me if the user interacts with the ViewPager while the fake drag animation is running. This is because in 4.1+ ViewPager.onInterceptTouchEvent nulls the mVelocityMonitor if it receives an ACTION_UP event. Since both fakeDrayBy and endFakeDrag use mVelocityMonitor (but do not create one) this gives us our NPE.

I fixed the problem by blocking touch events while my animation is running and by not allowing the animation to run if the user is interacting with the ViewPager.

**Comment by 2fours** [comment] 2013-07-21 20:20
I'm also seeing this with 2.4.1:

java.lang.NullPointerException at android.support.v4.view.ViewPager.fakeDragBy(ViewPager.java:2287) at com.viewpagerindicator.TitlePageIndicator.onTouchEvent(TitlePageIndicator.java:573) at android.view.View.dispatchTouchEvent(View.java:7246) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2196) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917) at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1953) at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1405) at android.app.Activity.dispatchTouchEvent(Activity.java:2410) at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1901) at android.view.View.dispatchPointerEvent(View.java:7426) at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3220) at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3165) at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4292) at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4271) at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4363) at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179) at android.os.MessageQueue.nativePollOnce(Native Method) at android.os.MessageQueue.next(MessageQueue.java:125) at android.os.Looper.loop(Looper.java:124) at android.app.ActivityThread.main(ActivityThread.java:5041) at java.lang.reflect.Method.invokeNative(Native Method) at java.lang.reflect.Method.invoke(Method.java:511) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) at dalvik.system.NativeStart.main(Native Method)

**Comment by yccheok** [comment] 2014-05-12 16:09
Similar problem right here too.

```
java.lang.NullPointerException
at android.support.v4.view.ViewPager.void fakeDragBy(float)(SourceFile:2366)
at com.viewpagerindicator.TitlePageIndicator.boolean onTouchEvent(android.view.MotionEvent)(SourceFile:573)
at android.view.View.dispatchTouchEvent(View.java:7706)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2238)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2068)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1515)
at android.app.Activity.dispatchTouchEvent(Activity.java:2458)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2016)
at android.view.View.dispatchPointerEvent(View.java:7886)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3954)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3833)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3449)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3418)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3525)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3426)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3582)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3449)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3418)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3426)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5602)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5582)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5553)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5682)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:138)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:5017)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
at dalvik.system.NativeStart.main(Native Method)
```
